use_frameworks!

platform :ios, '9.0'
source 'https://github.com/L3-iGrant/qr-code-scanner-ios.git'

target 'qr-code-scanner-ios_Example' do
  pod 'qr-code-scanner-ios'#, :path => '../'

  target 'qr-code-scanner-ios_Tests' do
    inherit! :search_paths
  end
end
