use_frameworks!

platform :ios, '9.0'

target 'qr-code-scanner-ios_Example' do
  pod 'qr-code-scanner-ios', :path => '../'

  target 'qr-code-scanner-ios_Tests' do
    inherit! :search_paths

    
  end
end
